export const Utils = {
    uuid() {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
            var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    },

    formatDate(dateStr) {
        if(!dateStr) return '';
        return new Date(dateStr).toLocaleDateString();
    },

    formatCurrency(amount) {
        return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);
    },

    downloadCSV(data, filename) {
        if (!data || !data.length) return;
        const keys = Object.keys(data[0]);
        const csvContent = [
            keys.join(','),
            ...data.map(row => keys.map(k => `"${String(row[k] || '').replace(/"/g, '""')}"`).join(','))
        ].join('\n');

        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement("a");
        const url = URL.createObjectURL(blob);
        link.setAttribute("href", url);
        link.setAttribute("download", filename);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    },

    async generatePDF(title, records, transactions, livestock, start, end) {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        // Header
        doc.setFillColor(46, 125, 50); // Primary color
        doc.rect(0, 0, 210, 20, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(16);
        doc.text("FarmTrack Report", 10, 13);
        
        doc.setTextColor(0,0,0);
        doc.setFontSize(12);
        doc.text(`Livestock: ${livestock.toUpperCase()}`, 10, 30);
        doc.text(`Period: ${start} to ${end}`, 10, 36);

        // Production Table
        const tableData = records.map(r => [
            r.date, 
            r.quantity || '-', 
            r.mortality || '-', 
            r.feedKg || '-', 
            r.notes || ''
        ]);

        doc.text("Production Records", 10, 45);
        doc.autoTable({
            startY: 50,
            head: [['Date', 'Qty', 'Mortality', 'Feed(kg)', 'Notes']],
            body: tableData,
            theme: 'striped',
        });

        // Transactions Table
        const lastY = doc.lastAutoTable.finalY + 10;
        doc.text("Financial Transactions", 10, lastY);
        
        const transData = transactions.map(t => [
            t.date, t.type.toUpperCase(), t.category, t.amount
        ]);

        doc.autoTable({
            startY: lastY + 5,
            head: [['Date', 'Type', 'Category', 'Amount']],
            body: transData,
            theme: 'grid'
        });

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        doc.setFontSize(8);
        for(let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.text('Generated by FarmTrack PWA', 10, 285);
        }

        doc.save(`farmtrack_report_${livestock}_${start}.pdf`);
    }
};
