export const Utils = {

    // Generates a RFC4122 version 4 compliant UUID

    uuid() {

        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {

            var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);

            return v.toString(16);

        });

    },



    formatDate(dateStr) {

        if(!dateStr) return '';

        return new Date(dateStr).toLocaleDateString(undefined, { 

            year: 'numeric', month: 'short', day: 'numeric' 

        });

    },



    // Updated to use a dynamic symbol based on app settings

    formatCurrency(amount, symbol = '$') {

        const formatted = new Intl.NumberFormat('en-US', { 

            minimumFractionDigits: 2, 

            maximumFractionDigits: 2 

        }).format(amount);

        return `${symbol} ${formatted}`;

    },



    downloadCSV(data, filename) {

        if (!data || !data.length) return;

        const keys = Object.keys(data[0]);

        const csvContent = [

            keys.join(','),

            ...data.map(row => keys.map(k => `"${String(row[k] || '').replace(/"/g, '""')}"`).join(','))

        ].join('\n');



        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });

        const link = document.createElement("a");

        const url = URL.createObjectURL(blob);

        link.setAttribute("href", url);

        link.setAttribute("download", filename);

        document.body.appendChild(link);

        link.click();

        document.body.removeChild(link);

    },



    async generatePDF(title, records, transactions, livestock, start, end) {

        const { jsPDF } = window.jspdf;

        const doc = new jsPDF();



        // Header Background

        doc.setFillColor(46, 125, 50); 

        doc.rect(0, 0, 210, 25, 'F');

        

        doc.setTextColor(255, 255, 255);

        doc.setFontSize(22);

        doc.text("FarmTrack Business Report", 15, 17);

        

        doc.setTextColor(80, 80, 80);

        doc.setFontSize(10);

        doc.text(`LIVESTOCK TYPE: ${livestock.toUpperCase()}`, 15, 35);

        doc.text(`REPORTING PERIOD: ${start} TO ${end}`, 15, 41);



        // PRODUCTION TABLE

        // We filter keys to ensure we don't print internal IDs in the PDF

        const prodKeys = records.length > 0 ? 

            Object.keys(records[0]).filter(k => !['id', 'livestock'].includes(k)) : [];

        

        const tableData = records.map(r => prodKeys.map(k => r[k] || '-'));



        doc.setFontSize(14);

        doc.setTextColor(46, 125, 50);

        doc.text("1. Production Activity", 15, 52);



        doc.autoTable({

            startY: 57,

            head: [prodKeys.map(k => k.charAt(0).toUpperCase() + k.slice(1))],

            body: tableData,

            theme: 'striped',

            headStyles: { fillColor: [46, 125, 50] }

        });



        // FINANCIAL TABLE

        const lastY = doc.lastAutoTable.finalY + 15;

        doc.text("2. Financial Transactions", 15, lastY);

        

        const transData = transactions.map(t => [

            t.date, 

            t.type.toUpperCase(), 

            t.category, 

            this.formatCurrency(t.amount, '') // Clean number for table

        ]);



        doc.autoTable({

            startY: lastY + 5,

            head: [['Date', 'Type', 'Category', 'Amount']],

            body: transData,

            theme: 'grid',

            headStyles: { fillColor: [70, 70, 70] }

        });



        // Footer

        const pageCount = doc.internal.getNumberOfPages();

        doc.setFontSize(8);

        doc.setTextColor(150, 150, 150);

        for(let i = 1; i <= pageCount; i++) {

            doc.setPage(i);

            doc.text(`Page ${i} of ${pageCount} - Generated by FarmTrack PWA`, 105, 285, { align: 'center' });

        }



        doc.save(`FarmTrack_${livestock}_${start}.pdf`);

    }

};
